### Import relevant libraries

In [1]:
import pandas as pd
import numpy as np

### Load dataset

In [2]:
image_encoder_type = 'clip'  # 'clip' or 'vit'
image_encoder_type

'clip'

In [3]:
if image_encoder_type == 'clip':
    # Load the data extracted from video frames using CLIP pretrained model
    df_action = pd.concat([pd.read_csv(f'../datasets/video_frame_features_clip_part_{part}.csv') for part in range(11)], ignore_index=True)
elif image_encoder_type == 'vit':
    # Load the data extracted from video frames using ViT pretrained model
    df_action = pd.concat([pd.read_csv(f'../datasets/video_frame_features_vit_part_{part}.csv') for part in range(7)], ignore_index=True)

In [6]:
df_action.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_506,feature_507,feature_508,feature_509,feature_510,feature_511,feature_512,video_file_name,label,subset
0,0.11690,0.4448,-0.1737,-0.3433,0.2805,-0.5390,0.07580,0.4333,0.1738,0.1970,...,0.1400,0.1581,0.10486,0.12050,0.8564,0.1821,-0.2695,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
1,0.09106,0.4558,-0.1633,-0.3250,0.2750,-0.5360,0.07350,0.4114,0.1816,0.1901,...,0.1428,0.1533,0.10394,0.10175,0.8520,0.1678,-0.2778,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
2,0.08700,0.4788,-0.1705,-0.3025,0.2750,-0.5290,0.06046,0.3342,0.1633,0.1840,...,0.1896,0.1456,0.07870,0.09350,0.7860,0.1888,-0.2861,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
3,0.09326,0.4612,-0.1779,-0.2720,0.2800,-0.5435,0.07220,0.3547,0.1958,0.1589,...,0.1838,0.1437,0.09760,0.07120,0.8420,0.1554,-0.2896,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
4,0.11554,0.4368,-0.1760,-0.2942,0.2590,-0.5405,0.09000,0.4282,0.1758,0.1663,...,0.1528,0.1553,0.06946,0.05768,0.8560,0.1431,-0.2732,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train

In [7]:
df_action.tail()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_506,feature_507,feature_508,feature_509,feature_510,feature_511,feature_512,video_file_name,label,subset
2165532,0.3410,0.11100,-0.03061,-0.2805,0.3506,-0.03029,0.0844,0.5540,0.09235,0.1257,...,0.08826,-0.1360,0.02605,0.375700,0.7188,-0.0933,0.34420,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165533,-0.1120,0.22510,-0.20760,-0.2440,0.4023,-0.77300,-0.2502,0.4280,0.30420,0.2210,...,0.01366,-0.2286,0.12730,0.120850,0.2053,0.0596,0.27200,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165534,-0.1327,0.11395,0.06384,-0.4907,0.3970,-0.76370,-0.3237,0.7050,0.02846,0.3057,...,-0.11194,-0.3557,0.39100,0.004276,0.0746,-0.2216,-0.06635,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165535,0.1952,-0.06134,0.09656,-0.1796,0.2913,-0.19480,-0.1727,0.8877,0.38800,0.3628,...,0.36450,-0.6760,-0.16990,-0.313700,0.4890,-0.2203,0.20360,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165536,0.1108,0.04700,0.16220,-0.2096,0.3398,-0.09420,-0.1884,0.6807,0.33600,0.3574,...,0.05720,-0.5645,-0.03867,-0.284400,0.3010,-0.1921,0.12520,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train

In [8]:
df_action.shape

(2165537, 515)

### Explore Data

In [9]:
# Check for missing values
df_action.isnull().sum()

feature_1          0
feature_2          0
feature_3          0
feature_4          0
feature_5          0
                  ..
feature_511        0
feature_512        0
video_file_name    0
label              0
subset             0
Length: 515, dtype: int64

In [10]:
# Check for label distribution
df_action['label'].value_counts()

label
abnormal    1310142
normal       855395
Name: count, dtype: int64

In [11]:
# Check number of unique video files per label
df_action.groupby('label')['video_file_name'].nunique()

label
abnormal    1230
normal      2562
Name: video_file_name, dtype: int64

In [12]:
# Check number of unieque video files
df_action['video_file_name'].nunique()

3792

In [13]:
# Check number of labels by subset
df_action.groupby('subset')['label'].value_counts()

subset  label
test    abnormal     175354
        normal       168288
train   abnormal    1026205
        normal       513270
val     normal       173837
        abnormal     108583
Name: count, dtype: int64

In [14]:
df_action.groupby(['subset', 'label'])['video_file_name'].nunique()

subset  label
test    abnormal     126
        normal       513
train   abnormal     980
        normal      1536
val     abnormal     124
        normal       513
Name: video_file_name, dtype: int64

In [15]:
# Check number of unique video files per subset
df_action.groupby('subset')['video_file_name'].nunique()

subset
test      639
train    2516
val       637
Name: video_file_name, dtype: int64

In [16]:
df_action['label'].unique()

array(['normal', 'abnormal'], dtype=object)

In [17]:
df_action['subset'].unique()

array(['train', 'val', 'test'], dtype=object)

### Data preparation

In [19]:
SEED = 42
np.random.seed(SEED)

In [20]:
# Helper function to convert series to supervised learning
def series_to_supervised(data, column_names, n_in=1, n_out=1, dropnan=True, n_out_index=None, is_drop_target=False, lag_sampling=1, sliding_stride=1):
    """
    convert series to supervised learning
    Params:
    - n_in: number of timesteps
    - n_out: number of output timestep for prediction | eg. 1 day, 2 days, ....
    - n_out_index: define specific variable for prediction
    - is_drop_target: drop target variable from input variables (to be used for classification problem)
    - lag_sampling: lag sampling stride (to skip some samples within a window)
    - sliding_stride: sliding window stride (to skip some windows)
    - dropnan: boolean whether or not to drop rows with NaN values
    Returns:
    - Pandas DataFrame of series framed for supervised learning.
    """
    df_new = pd.DataFrame(data)
    
    if is_drop_target:
        df_input = df_new.drop(columns=[column_names[n_out_index]])
    else:
        df_input = df_new.copy()
    
    n_vars = df_input.shape[1]
    
    cols, names = list(), list()
    
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -lag_sampling):
        cols.append(df_input.shift(i))
        names += [f'{column_names[j]}(t-{i})' for j in range(n_vars)]
    
    # forecast sequence (t, t+1, ..., t+n)
    for i in range(0, n_out):
        if n_out_index:
            cols.append(df_new.shift(-i).iloc[:, n_out_index])
            if i == 0:
                names += [f'{column_names[n_out_index]}(t)']
            else:
                names += [f'{column_names[n_out_index]}(t+{i})']
        else:
            cols.append(df_new.shift(-i))
            if i == 0:
                names += [f'{column_names[j]}(t)' for j in range(n_vars)]
            else:
                names += [f'{column_names[j]}(t+{i})' for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names

    # drop some rows to avoid many duplicate rows
    if agg.shape[0] > 300:
        # drop first 10% and last 10% of rows
        agg = agg.iloc[int(0.1 * agg.shape[0]): int(0.9 * agg.shape[0]), :]

    # drop rows with NaN values that generated from df_new.shift
    if dropnan:
        agg.dropna(inplace=True)

    # Use slicing to select only the rows corresponding to the desired stride
    if sliding_stride > 1:
        agg = agg.iloc[::sliding_stride, :]
    
    return agg

In [21]:
# define features
column_names = df_action.columns.tolist()
column_names.remove('video_file_name')
column_names.remove('subset')
column_names

['feature_1',
 'feature_2',
 'feature_3',
 'feature_4',
 'feature_5',
 'feature_6',
 'feature_7',
 'feature_8',
 'feature_9',
 'feature_10',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_14',
 'feature_15',
 'feature_16',
 'feature_17',
 'feature_18',
 'feature_19',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_27',
 'feature_28',
 'feature_29',
 'feature_30',
 'feature_31',
 'feature_32',
 'feature_33',
 'feature_34',
 'feature_35',
 'feature_36',
 'feature_37',
 'feature_38',
 'feature_39',
 'feature_40',
 'feature_41',
 'feature_42',
 'feature_43',
 'feature_44',
 'feature_45',
 'feature_46',
 'feature_47',
 'feature_48',
 'feature_49',
 'feature_50',
 'feature_51',
 'feature_52',
 'feature_53',
 'feature_54',
 'feature_55',
 'feature_56',
 'feature_57',
 'feature_58',
 'feature_59',
 'feature_60',
 'feature_61',
 'feature_62',
 'feature_63',
 'feature_64',
 'feature_65',
 'feature_66',
 'feature_67',
 'feature_68',
 'feature_69',
 'feature_70',
 'feature_71',
 'feature_72',
 'feature_73',
 'feature_74',
 'feature_75',
 'feature_76',
 'feature_77',
 'feature_78',
 'feature_79',
 'feature_80',
 'feature_81',
 'feature_82',
 'feature_83',
 'feature_84',
 'feature_85',
 'feature_86',
 'feature_87',
 'feature_88',
 'feature_89',
 'feature_90',
 'feature_91',
 'feature_92',
 'feature_93',
 'feature_94',
 'feature_95',
 'feature_96',
 'feature_97',
 'feature_98',
 'feature_99',
 'feature_100',
 'feature_101',
 'feature_102',
 'feature_103',
 'feature_104',
 'feature_105',
 'feature_106',
 'feature_107',
 'feature_108',
 'feature_109',
 'feature_110',
 'feature_111',
 'feature_112',
 'feature_113',
 'feature_114',
 'feature_115',
 'feature_116',
 'feature_117',
 'feature_118',
 'feature_119',
 'feature_120',
 'feature_121',
 'feature_122',
 'feature_123',
 'feature_124',
 'feature_125',
 'feature_126',
 'feature_127',
 'feature_128',
 'feature_129',
 'feature_130',
 'feature_131',
 'feature_132',
 'feature_133',
 'feature_134',
 'feature_135',
 'feature_136',
 'feature_137',
 'feature_138',
 'feature_139',
 'feature_140',
 'feature_141',
 'feature_142',
 'feature_143',
 'feature_144',
 'feature_145',
 'feature_146',
 'feature_147',
 'feature_148',
 'feature_149',
 'feature_150',
 'feature_151',
 'feature_152',
 'feature_153',
 'feature_154',
 'feature_155',
 'feature_156',
 'feature_157',
 'feature_158',
 'feature_159',
 'feature_160',
 'feature_161',
 'feature_162',
 'feature_163',
 'feature_164',
 'feature_165',
 'feature_166',
 'feature_167',
 'feature_168',
 'feature_169',
 'feature_170',
 'feature_171',
 'feature_172',
 'feature_173',
 'feature_174',
 'feature_175',
 'feature_176',
 'feature_177',
 'feature_178',
 'feature_179',
 'feature_180',
 'feature_181',
 'feature_182',
 'feature_183',
 'feature_184',
 'feature_185',
 'feature_186',
 'feature_187',
 'feature_188',
 'feature_189',
 'feature_190',
 'feature_191',
 'feature_192',
 'feature_193',
 'feature_194',
 'feature_195',
 'feature_196',
 'feature_197',
 'feature_198',
 'feature_199',
 'feature_200',
 'feature_201',
 'feature_202',
 'feature_203',
 'feature_204',
 'feature_205',
 'feature_206',
 'feature_207',
 'feature_208',
 'feature_209',
 'feature_210',
 'feature_211',
 'feature_212',
 'feature_213',
 'feature_214',
 'feature_215',
 'feature_216',
 'feature_217',
 'feature_218',
 'feature_219',
 'feature_220',
 'feature_221',
 'feature_222',
 'feature_223',
 'feature_224',
 'feature_225',
 'feature_226',
 'feature_227',
 'feature_228',
 'feature_229',
 'feature_230',
 'feature_231',
 'feature_232',
 'feature_233',
 'feature_234',
 'feature_235',
 'feature_236',
 'feature_237',
 'feature_238',
 'feature_239',
 'feature_240',
 'feature_241',
 'feature_242',
 'feature_243',
 'feature_244',
 'feature_245',
 'feature_246',
 'feature_247',
 'feature_248',
 'feature_249',
 'feature_250',
 'feature_251',
 'feature_252',
 'feature_253',
 'feature_254',
 'feature_255',
 'feature_256',
 'feature_257',
 'feature_258',
 'feature_259',
 'feature_260',
 'feature_261',
 'feature_262',
 'feature_263',
 'feature_264',
 'feature_265',
 'feature_266',
 'feature_267',
 'feature_268',
 'feature_269',
 'feature_270',
 'feature_271',
 'feature_272',
 'feature_273',
 'feature_274',
 'feature_275',
 'feature_276',
 'feature_277',
 'feature_278',
 'feature_279',
 'feature_280',
 'feature_281',
 'feature_282',
 'feature_283',
 'feature_284',
 'feature_285',
 'feature_286',
 'feature_287',
 'feature_288',
 'feature_289',
 'feature_290',
 'feature_291',
 'feature_292',
 'feature_293',
 'feature_294',
 'feature_295',
 'feature_296',
 'feature_297',
 'feature_298',
 'feature_299',
 'feature_300',
 'feature_301',
 'feature_302',
 'feature_303',
 'feature_304',
 'feature_305',
 'feature_306',
 'feature_307',
 'feature_308',
 'feature_309',
 'feature_310',
 'feature_311',
 'feature_312',
 'feature_313',
 'feature_314',
 'feature_315',
 'feature_316',
 'feature_317',
 'feature_318',
 'feature_319',
 'feature_320',
 'feature_321',
 'feature_322',
 'feature_323',
 'feature_324',
 'feature_325',
 'feature_326',
 'feature_327',
 'feature_328',
 'feature_329',
 'feature_330',
 'feature_331',
 'feature_332',
 'feature_333',
 'feature_334',
 'feature_335',
 'feature_336',
 'feature_337',
 'feature_338',
 'feature_339',
 'feature_340',
 'feature_341',
 'feature_342',
 'feature_343',
 'feature_344',
 'feature_345',
 'feature_346',
 'feature_347',
 'feature_348',
 'feature_349',
 'feature_350',
 'feature_351',
 'feature_352',
 'feature_353',
 'feature_354',
 'feature_355',
 'feature_356',
 'feature_357',
 'feature_358',
 'feature_359',
 'feature_360',
 'feature_361',
 'feature_362',
 'feature_363',
 'feature_364',
 'feature_365',
 'feature_366',
 'feature_367',
 'feature_368',
 'feature_369',
 'feature_370',
 'feature_371',
 'feature_372',
 'feature_373',
 'feature_374',
 'feature_375',
 'feature_376',
 'feature_377',
 'feature_378',
 'feature_379',
 'feature_380',
 'feature_381',
 'feature_382',
 'feature_383',
 'feature_384',
 'feature_385',
 'feature_386',
 'feature_387',
 'feature_388',
 'feature_389',
 'feature_390',
 'feature_391',
 'feature_392',
 'feature_393',
 'feature_394',
 'feature_395',
 'feature_396',
 'feature_397',
 'feature_398',
 'feature_399',
 'feature_400',
 'feature_401',
 'feature_402',
 'feature_403',
 'feature_404',
 'feature_405',
 'feature_406',
 'feature_407',
 'feature_408',
 'feature_409',
 'feature_410',
 'feature_411',
 'feature_412',
 'feature_413',
 'feature_414',
 'feature_415',
 'feature_416',
 'feature_417',
 'feature_418',
 'feature_419',
 'feature_420',
 'feature_421',
 'feature_422',
 'feature_423',
 'feature_424',
 'feature_425',
 'feature_426',
 'feature_427',
 'feature_428',
 'feature_429',
 'feature_430',
 'feature_431',
 'feature_432',
 'feature_433',
 'feature_434',
 'feature_435',
 'feature_436',
 'feature_437',
 'feature_438',
 'feature_439',
 'feature_440',
 'feature_441',
 'feature_442',
 'feature_443',
 'feature_444',
 'feature_445',
 'feature_446',
 'feature_447',
 'feature_448',
 'feature_449',
 'feature_450',
 'feature_451',
 'feature_452',
 'feature_453',
 'feature_454',
 'feature_455',
 'feature_456',
 'feature_457',
 'feature_458',
 'feature_459',
 'feature_460',
 'feature_461',
 'feature_462',
 'feature_463',
 'feature_464',
 'feature_465',
 'feature_466',
 'feature_467',
 'feature_468',
 'feature_469',
 'feature_470',
 'feature_471',
 'feature_472',
 'feature_473',
 'feature_474',
 'feature_475',
 'feature_476',
 'feature_477',
 'feature_478',
 'feature_479',
 'feature_480',
 'feature_481',
 'feature_482',
 'feature_483',
 'feature_484',
 'feature_485',
 'feature_486',
 'feature_487',
 'feature_488',
 'feature_489',
 'feature_490',
 'feature_491',
 'feature_492',
 'feature_493',
 'feature_494',
 'feature_495',
 'feature_496',
 'feature_497',
 'feature_498',
 'feature_499',
 'feature_500',
 'feature_501',
 'feature_502',
 'feature_503',
 'feature_504',
 'feature_505',
 'feature_506',
 'feature_507',
 'feature_508',
 'feature_509',
 'feature_510',
 'feature_511',
 'feature_512',
 'label']

In [22]:
# Define window_size (number of timesteps or number of frames), number of features, and number of output step
window_size = 120 # number of frames within a window
lag_sampling =  5 # step size for selecting frames within a window
sliding_stride = 4 # sliding window stride
num_features = len(column_names[:-1])
n_steps_out = 1
n_out_index =  -1

In [23]:
is_save_supervised_features_into_file = False # To reduce memory issue when the variable is set to True

In [25]:
# Reframe as supervised learning by each video file
subsets = df_action['subset'].unique()
df_by_subset = {}

for subset in subsets:
    print(f'Processing subset: {subset}')
    df_action_subset = df_action[df_action['subset'] == subset]
    video_files = df_action_subset['video_file_name'].unique()

    dfs = []
    n_skip = 0
    for i, video_file in enumerate(video_files):
        print(f'Processing video file {i+1}/{len(video_files)}: {video_file}'.ljust(200), end='\r')
        
        df_video = df_action_subset[df_action_subset['video_file_name'] == video_file]

        if df_video.shape[0] < int(window_size/lag_sampling):
            n_skip += 1
            continue
        elif df_video.shape[0] < window_size:
            # Pad 0 first 512 columns to make sure we have enough frames within a window
            pad_width = window_size - df_video.shape[0] + 1
            df_video = pd.concat([df_video, pd.DataFrame(np.nan, index=np.arange(pad_width), columns=df_video.columns[:-3])], ignore_index=True)
            # Fill NaN value on first 512 columns values by mode of each column
            df_video.iloc[:, :-3].fillna(df_video.iloc[:, :-3].mode(), inplace=True)
            # Fill NaN values on last 3 column by previous values
            df_video.ffill(inplace=True)

        df_reframed = series_to_supervised(
            df_video.drop(columns=['video_file_name', 'subset']),
            column_names,
            n_in=window_size,
            n_out=n_steps_out,
            n_out_index=n_out_index,
            is_drop_target=True,
            lag_sampling=lag_sampling,
            sliding_stride=sliding_stride
        )
        
        if is_save_supervised_features_into_file:
            # Check if dataframe is not empty
            if not df_reframed.empty:
                df_reframed.to_csv(f'../datasets/supervised_features_tmp/{subset}/supervised_features_{image_encoder_type}_{video_file}.csv', index=False)
        else:
            dfs.append(df_reframed)

    if not is_save_supervised_features_into_file:
        df_subset = pd.concat(dfs, ignore_index=True)
        df_by_subset[subset] = df_subset
    print(f"Finished processing subset: {subset}. Skipped {n_skip} videos.".ljust(200))

Processing subset: train
Finished processing subset: train. Skipped 9 videos.
Processing subset: val
Finished processing subset: val. Skipped 1 videos.
Processing subset: test
Finished processing subset: test. Skipped 2 videos.

In [26]:
import os

if is_save_supervised_features_into_file:
    for subset in subsets:
        print(f'Loading saved supervised features for subset: {subset}')
        all_files = os.listdir(f'../datasets/supervised_features_tmp/{subset}')
        df_by_subset[subset] = pd.concat([pd.read_csv(f'../datasets/supervised_features_tmp/{subset}/{file}') for file in all_files], ignore_index=True)

In [27]:
df_by_subset['train'].head()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_504(t-5),feature_505(t-5),feature_506(t-5),feature_507(t-5),feature_508(t-5),feature_509(t-5),feature_510(t-5),feature_511(t-5),feature_512(t-5),label(t)
0,0.11690,0.4448,-0.1737,-0.3433,0.2805,-0.5390,0.075800,0.4333,0.1738,0.1970,...,0.1019,0.23660,-0.1814,0.1740,0.1599,0.05396,1.092,0.1870,-0.4300,normal
1,0.11554,0.4368,-0.1760,-0.2942,0.2590,-0.5405,0.090000,0.4282,0.1758,0.1663,...,0.2343,0.21530,-0.3403,0.3254,0.1036,0.05950,1.172,0.2382,-0.2651,normal
2,0.15450,0.4324,-0.1823,-0.3438,0.2544,-0.5234,-0.000469,0.4453,0.2042,0.1832,...,0.2179,0.18030,-0.1738,0.3762,0.2178,0.01698,1.262,0.1644,-0.2479,normal
3,0.10860,0.3887,-0.1974,-0.2961,0.2300,-0.5260,0.013280,0.4758,0.2384,0.1263,...,0.2288,0.10254,-0.1917,0.2742,0.2164,-0.07960,1.023,0.2057,-0.2760,normal
4,0.10730,0.3708,-0.1788,-0.2632,0.2106,-0.5630,0.015900,0.5020,0.2502,0.1184,...,0.1709,0.26980,-0.0520,0.2107,0.1827,-0.03380,0.998,0.1815,-0.3533,normal

In [28]:
# Check dataframes size for each subset
for key in df_by_subset.keys():
    print(f'Subset: {key}, Shape: {df_by_subset[key].shape}')

Subset: train, Shape: (272569, 12289)
Subset: val, Shape: (47271, 12289)
Subset: test, Shape: (59357, 12289)

In [29]:
# Rename label column
for key in df_by_subset.keys():
    df_by_subset[key].rename(columns={f'label(t)': 'label'}, inplace=True)

In [30]:
# Check label distribution for each subset
for key in df_by_subset.keys():
    print(f'Subset: {key} \n{df_by_subset[key]["label"].value_counts()}')

Subset: train
label
abnormal    193447
normal       79122
Name: count, dtype: int64
Subset: val
label
normal      26905
abnormal    20366
Name: count, dtype: int64
Subset: test
label
abnormal    33574
normal      25783
Name: count, dtype: int64

In [32]:
# Define sample size for each subset
sample_size = {
    'train': 120000,
    'val': 15000,
    'test': 15000
}

In [33]:
# Sample data for each subset
df_train = pd.concat([df_by_subset['train'][df_by_subset['train']['label'] == label].sample(n=int(sample_size['train']/2), random_state=SEED) for label in df_by_subset['train']['label'].unique()])
df_train.shape

(120000, 12289)

In [34]:
df_val = pd.concat([df_by_subset['val'][df_by_subset['val']['label'] == label].sample(n=int(sample_size['val']/2), random_state=SEED) for label in df_by_subset['val']['label'].unique()])
df_val.shape

(15000, 12289)

In [35]:
df_test = pd.concat([df_by_subset['test'][df_by_subset['test']['label'] == label].sample(n=int(sample_size['test']/2), random_state=SEED) for label in df_by_subset['test']['label'].unique()])
df_test.shape

(15000, 12289)

In [36]:
# Check label distribution after sampling
print(f'Train label distribution:\n{df_train["label"].value_counts()}') 
print(f'Validation label distribution:\n{df_val["label"].value_counts()}')
print(f'Test label distribution:\n{df_test["label"].value_counts()}')

Train label distribution:
label
normal      60000
abnormal    60000
Name: count, dtype: int64
Validation label distribution:
label
normal      7500
abnormal    7500
Name: count, dtype: int64
Test label distribution:
label
normal      7500
abnormal    7500
Name: count, dtype: int64

In [37]:
# Convert labels to binary (0: abnormal, 1: normal)
df_train['label'] = df_train['label'].map(lambda x: 0 if x == 'normal' else 1)
df_val['label'] = df_val['label'].map(lambda x: 0 if x == 'normal' else 1)
df_test['label'] = df_test['label'].map(lambda x: 0 if x == 'normal' else 1)

In [38]:
df_train.head()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_504(t-5),feature_505(t-5),feature_506(t-5),feature_507(t-5),feature_508(t-5),feature_509(t-5),feature_510(t-5),feature_511(t-5),feature_512(t-5),label
55969,0.77400,0.00163,0.14870,-0.1965,0.42550,-0.1849,0.30420,0.5356,0.7324,0.3542,...,-0.002094,-0.1993,-0.20980,0.12476,-0.1842,0.2131,0.4614,0.2230,-0.45210,0
35936,0.32620,-0.31960,0.09830,-0.2126,-0.13170,-0.2840,-0.15450,0.4612,0.2634,0.4792,...,0.314700,0.3662,0.01373,-0.30300,-0.3270,-0.4321,0.4540,0.1748,-0.02936,0
68191,0.03647,-0.08190,-0.08966,0.1387,-0.11035,0.1473,0.16560,0.5830,0.0660,0.2812,...,0.313000,0.3928,-0.24550,-0.06610,0.2180,-0.3235,0.7925,-0.0663,0.10810,0
42540,-0.34670,-0.15600,-0.47140,-0.1436,0.18370,-0.1364,-0.01563,1.0460,0.4697,-0.2103,...,-0.015850,0.5664,-0.20570,-0.34840,-0.1815,-0.2023,1.1040,0.0238,-0.13090,0
56580,0.33200,0.03156,-0.16540,-0.2854,0.01439,-0.4450,0.41970,0.6610,0.4434,0.1317,...,0.118100,0.4429,0.26930,-0.20000,-0.1370,-0.3125,0.8394,-0.2788,0.21030,0

In [39]:
df_train.tail()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_504(t-5),feature_505(t-5),feature_506(t-5),feature_507(t-5),feature_508(t-5),feature_509(t-5),feature_510(t-5),feature_511(t-5),feature_512(t-5),label
127042,0.06207,0.214000,0.15220,-0.56640,0.23230,-0.4338,0.18190,0.3347,0.1855,0.40260,...,0.03784,-0.2930,-0.1274,-0.28660,-0.03494,0.07166,0.4136,0.28960,-0.30180,1
222770,0.37100,0.181600,0.35720,-0.42600,0.13220,-0.0814,0.29600,-0.2230,-0.1176,-0.02165,...,-0.13050,0.1855,-0.2656,0.06384,0.33130,-0.12305,1.0110,-0.02344,0.04843,1
190276,0.40010,-0.000126,0.68000,-0.28080,-0.37160,-0.2803,-0.01039,-0.0707,-0.2793,-0.22510,...,-0.21660,0.7656,-0.3835,0.11554,0.53270,0.13530,0.4426,0.22800,0.30180,1
119937,0.33840,0.264000,0.01935,0.04614,0.37000,-0.8260,0.20060,0.3000,0.6220,0.14030,...,-0.08550,0.6940,0.2231,-0.21770,-0.46000,0.10460,0.4040,-0.31320,-0.08470,1
122837,0.20950,-0.280800,0.04343,-0.13760,0.00475,-0.1214,0.31180,-0.2302,-0.2712,-0.03910,...,-0.35770,0.7476,-0.2236,0.00626,0.28080,-0.10150,0.5550,-0.01924,-0.12900,1

In [40]:
# Reshape data for model training
X_train, y_train = df_train.drop(columns=['label']).values, df_train['label'].values
X_val, y_val = df_val.drop(columns=['label']).values, df_val['label'].values
X_test, y_test = df_test.drop(columns=['label']).values, df_test['label'].values

effective_window_size = int(window_size / lag_sampling)
X_train = X_train.reshape((-1, effective_window_size, num_features))
X_val = X_val.reshape((-1, effective_window_size, num_features))
X_test = X_test.reshape((-1, effective_window_size, num_features))

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((120000, 24, 512),
 (120000,),
 (15000, 24, 512),
 (15000,),
 (15000, 24, 512),
 (15000,))

In [41]:
# Save processed data to csv files
np.savez_compressed(f'../datasets/video_frame_features_{image_encoder_type}_ws{window_size}_ls{lag_sampling}_st{sliding_stride}_supervised_data.npz', 
                    X_train=X_train, y_train=y_train, 
                    X_val=X_val, y_val=y_val, 
                    X_test=X_test, y_test=y_test)