### Import relevant libraries

In [1]:
import pandas as pd
import numpy as np

### Load dataset

In [2]:
image_encoder_type = 'vit'  # 'clip' or 'vit'
image_encoder_type

'vit'

In [3]:
if image_encoder_type == 'clip':
    # Load the data extracted from video frames using CLIP pretrained model
    df_action = pd.concat([pd.read_csv(f'../datasets/{image_encoder_type}/video_frame_features_clip_part_{part}.csv') for part in range(11)], ignore_index=True)
elif image_encoder_type == 'vit':
    # Load the data extracted from video frames using ViT pretrained model
    df_action = pd.concat([pd.read_csv(f'../datasets/{image_encoder_type}/video_frame_features_vit_part_{part}.csv') for part in range(22)], ignore_index=True)

In [4]:
df_action.head()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_762,feature_763,feature_764,feature_765,feature_766,feature_767,feature_768,video_file_name,label,subset
0,-0.433573,1.382384,1.610541,-0.475232,0.207636,-0.199758,-0.117489,1.316876,-0.965239,0.167614,...,-0.741849,-0.558131,-0.342523,0.730184,1.590018,1.197356,-0.822331,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
1,-0.389260,1.413584,1.586250,-0.510316,0.113294,-0.180350,-0.081446,1.351847,-0.916350,0.200261,...,-0.742581,-0.641726,-0.351214,0.735414,1.604405,1.164891,-0.879187,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
2,-0.341629,1.411383,1.473647,-0.470251,0.148228,-0.152102,-0.027801,1.351231,-1.106200,0.271080,...,-0.772509,-0.696967,-0.376834,0.803685,1.656675,1.012231,-0.902771,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
3,-0.363553,1.334279,1.604678,-0.562663,0.244192,-0.402394,0.149826,1.341739,-1.181335,0.048575,...,-0.733624,-0.870912,-0.464521,0.609401,1.729759,1.157164,-0.788112,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train
4,-0.295375,1.359978,1.598993,-0.322180,0.247712,-0.536664,0.157162,1.389684,-1.175561,0.073235,...,-0.616147,-0.837130,-0.568376,0.555641,1.787494,1.334162,-0.754414,virat_VIRAT_S_010001_05_000649_000684_carrying...,normal,train

In [5]:
df_action.tail()

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_762,feature_763,feature_764,feature_765,feature_766,feature_767,feature_768,video_file_name,label,subset
2165532,-1.903107,-0.299456,1.194561,-0.564283,-2.271185,-0.238523,1.648342,2.625114,-0.570375,1.399951,...,-1.022099,-0.301020,1.680913,-0.012018,-0.907245,-2.066085,-0.117639,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165533,-1.803633,-0.606809,1.210989,0.107957,-1.980269,-0.837765,0.701346,2.266091,0.323197,1.580440,...,-1.511564,-1.763999,1.735174,-0.136686,-0.923441,-1.724476,1.069400,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165534,-1.122570,0.065944,1.278655,0.571338,-0.477410,-0.096399,0.961536,2.431973,0.068020,0.598312,...,-1.046401,-1.434949,1.110209,0.138756,0.203081,-1.294247,1.441706,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165535,-1.073448,0.391527,1.348591,0.100530,-0.826118,-0.558868,1.368353,2.359297,-0.040773,0.914979,...,-1.071985,-1.500945,1.495499,0.230144,-0.054068,-1.465915,1.585537,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train
2165536,-1.654409,0.163688,1.262409,-0.396127,-1.859544,0.020625,1.325322,2.845811,-0.265951,1.742987,...,-1.319171,-1.176149,1.385815,0.436892,-0.885270,-1.967522,0.514656,uccrime_Vandalism025_x264_trimmed_augmented.mp4,abnormal,train

In [6]:
df_action.shape

(2165537, 771)

### Explore Data

In [7]:
# Check for missing values
df_action.isnull().sum()

feature_1          0
feature_2          0
feature_3          0
feature_4          0
feature_5          0
                  ..
feature_767        0
feature_768        0
video_file_name    0
label              0
subset             0
Length: 771, dtype: int64

In [8]:
# Check for label distribution
df_action['label'].value_counts()

label
abnormal    1310142
normal       855395
Name: count, dtype: int64

In [9]:
# Check number of unique video files per label
df_action.groupby('label')['video_file_name'].nunique()

label
abnormal    1230
normal      2562
Name: video_file_name, dtype: int64

In [10]:
# Check number of unieque video files
df_action['video_file_name'].nunique()

3792

In [11]:
# Check number of labels by subset
df_action.groupby('subset')['label'].value_counts()

subset  label
test    abnormal     175354
        normal       168288
train   abnormal    1026205
        normal       513270
val     normal       173837
        abnormal     108583
Name: count, dtype: int64

In [12]:
df_action.groupby(['subset', 'label'])['video_file_name'].nunique()

subset  label
test    abnormal     126
        normal       513
train   abnormal     980
        normal      1536
val     abnormal     124
        normal       513
Name: video_file_name, dtype: int64

In [13]:
# Check number of unique video files per subset
df_action.groupby('subset')['video_file_name'].nunique()

subset
test      639
train    2516
val       637
Name: video_file_name, dtype: int64

In [14]:
df_action['label'].unique()

array(['normal', 'abnormal'], dtype=object)

In [15]:
df_action['subset'].unique()

array(['train', 'val', 'test'], dtype=object)

### Data preparation

In [16]:
SEED = 42
np.random.seed(SEED)

In [17]:
# Helper function to convert series to supervised learning
def series_to_supervised(data, column_names, n_in=1, n_out=1, dropnan=True, n_out_index=None, is_drop_target=False, lag_sampling=1, sliding_stride=1):
    """
    convert series to supervised learning
    Params:
    - n_in: number of timesteps
    - n_out: number of output timestep for prediction | eg. 1 day, 2 days, ....
    - n_out_index: define specific variable for prediction
    - is_drop_target: drop target variable from input variables (to be used for classification problem)
    - lag_sampling: lag sampling stride (to skip some samples within a window)
    - sliding_stride: sliding window stride (to skip some windows)
    - dropnan: boolean whether or not to drop rows with NaN values
    Returns:
    - Pandas DataFrame of series framed for supervised learning.
    """
    df_new = pd.DataFrame(data)
    
    if is_drop_target:
        df_input = df_new.drop(columns=[column_names[n_out_index]])
    else:
        df_input = df_new.copy()
    
    n_vars = df_input.shape[1]
    
    cols, names = list(), list()
    
    # input sequence (t-n, ... t-1)
    for i in range(n_in, 0, -lag_sampling):
        cols.append(df_input.shift(i))
        names += [f'{column_names[j]}(t-{i})' for j in range(n_vars)]
    
    # forecast sequence (t, t+1, ..., t+n)
    for i in range(0, n_out):
        if n_out_index:
            cols.append(df_new.shift(-i).iloc[:, n_out_index])
            if i == 0:
                names += [f'{column_names[n_out_index]}(t)']
            else:
                names += [f'{column_names[n_out_index]}(t+{i})']
        else:
            cols.append(df_new.shift(-i))
            if i == 0:
                names += [f'{column_names[j]}(t)' for j in range(n_vars)]
            else:
                names += [f'{column_names[j]}(t+{i})' for j in range(n_vars)]
    # put it all together
    agg = pd.concat(cols, axis=1)
    agg.columns = names

    # drop some rows to avoid many duplicate rows 
    # if it has more than 300 rows
    if agg.shape[0] > 300:
        # drop first 20% and last 20% of rows
        agg = agg.iloc[int(0.2 * agg.shape[0]): int(0.8 * agg.shape[0]), :]

    # drop rows with NaN values that generated from df_new.shift
    if dropnan:
        agg.dropna(inplace=True)

    # Use slicing to select only the rows corresponding to the desired stride
    if sliding_stride > 1:
        agg = agg.iloc[::sliding_stride, :]
    
    return agg

In [18]:
# define features
column_names = df_action.columns.tolist()
column_names.remove('video_file_name')
column_names.remove('subset')
column_names

['feature_1',
 'feature_2',
 'feature_3',
 'feature_4',
 'feature_5',
 'feature_6',
 'feature_7',
 'feature_8',
 'feature_9',
 'feature_10',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_14',
 'feature_15',
 'feature_16',
 'feature_17',
 'feature_18',
 'feature_19',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_27',
 'feature_28',
 'feature_29',
 'feature_30',
 'feature_31',
 'feature_32',
 'feature_33',
 'feature_34',
 'feature_35',
 'feature_36',
 'feature_37',
 'feature_38',
 'feature_39',
 'feature_40',
 'feature_41',
 'feature_42',
 'feature_43',
 'feature_44',
 'feature_45',
 'feature_46',
 'feature_47',
 'feature_48',
 'feature_49',
 'feature_50',
 'feature_51',
 'feature_52',
 'feature_53',
 'feature_54',
 'feature_55',
 'feature_56',
 'feature_57',
 'feature_58',
 'feature_59',
 'feature_60',
 'feature_61',
 'feature_62',
 'feature_63',
 'feature_64',
 'feature_65',
 'feature_66',
 'feature_67',
 'feature_68',
 'feature_69',
 'feature_70',
 'feature_71',
 'feature_72',
 'feature_73',
 'feature_74',
 'feature_75',
 'feature_76',
 'feature_77',
 'feature_78',
 'feature_79',
 'feature_80',
 'feature_81',
 'feature_82',
 'feature_83',
 'feature_84',
 'feature_85',
 'feature_86',
 'feature_87',
 'feature_88',
 'feature_89',
 'feature_90',
 'feature_91',
 'feature_92',
 'feature_93',
 'feature_94',
 'feature_95',
 'feature_96',
 'feature_97',
 'feature_98',
 'feature_99',
 'feature_100',
 'feature_101',
 'feature_102',
 'feature_103',
 'feature_104',
 'feature_105',
 'feature_106',
 'feature_107',
 'feature_108',
 'feature_109',
 'feature_110',
 'feature_111',
 'feature_112',
 'feature_113',
 'feature_114',
 'feature_115',
 'feature_116',
 'feature_117',
 'feature_118',
 'feature_119',
 'feature_120',
 'feature_121',
 'feature_122',
 'feature_123',
 'feature_124',
 'feature_125',
 'feature_126',
 'feature_127',
 'feature_128',
 'feature_129',
 'feature_130',
 'feature_131',
 'feature_132',
 'feature_133',
 'feature_134',
 'feature_135',
 'feature_136',
 'feature_137',
 'feature_138',
 'feature_139',
 'feature_140',
 'feature_141',
 'feature_142',
 'feature_143',
 'feature_144',
 'feature_145',
 'feature_146',
 'feature_147',
 'feature_148',
 'feature_149',
 'feature_150',
 'feature_151',
 'feature_152',
 'feature_153',
 'feature_154',
 'feature_155',
 'feature_156',
 'feature_157',
 'feature_158',
 'feature_159',
 'feature_160',
 'feature_161',
 'feature_162',
 'feature_163',
 'feature_164',
 'feature_165',
 'feature_166',
 'feature_167',
 'feature_168',
 'feature_169',
 'feature_170',
 'feature_171',
 'feature_172',
 'feature_173',
 'feature_174',
 'feature_175',
 'feature_176',
 'feature_177',
 'feature_178',
 'feature_179',
 'feature_180',
 'feature_181',
 'feature_182',
 'feature_183',
 'feature_184',
 'feature_185',
 'feature_186',
 'feature_187',
 'feature_188',
 'feature_189',
 'feature_190',
 'feature_191',
 'feature_192',
 'feature_193',
 'feature_194',
 'feature_195',
 'feature_196',
 'feature_197',
 'feature_198',
 'feature_199',
 'feature_200',
 'feature_201',
 'feature_202',
 'feature_203',
 'feature_204',
 'feature_205',
 'feature_206',
 'feature_207',
 'feature_208',
 'feature_209',
 'feature_210',
 'feature_211',
 'feature_212',
 'feature_213',
 'feature_214',
 'feature_215',
 'feature_216',
 'feature_217',
 'feature_218',
 'feature_219',
 'feature_220',
 'feature_221',
 'feature_222',
 'feature_223',
 'feature_224',
 'feature_225',
 'feature_226',
 'feature_227',
 'feature_228',
 'feature_229',
 'feature_230',
 'feature_231',
 'feature_232',
 'feature_233',
 'feature_234',
 'feature_235',
 'feature_236',
 'feature_237',
 'feature_238',
 'feature_239',
 'feature_240',
 'feature_241',
 'feature_242',
 'feature_243',
 'feature_244',
 'feature_245',
 'feature_246',
 'feature_247',
 'feature_248',
 'feature_249',
 'feature_250',
 'feature_251',
 'feature_252',
 'feature_253',
 'feature_254',
 'feature_255',
 'feature_256',
 'feature_257',
 'feature_258',
 'feature_259',
 'feature_260',
 'feature_261',
 'feature_262',
 'feature_263',
 'feature_264',
 'feature_265',
 'feature_266',
 'feature_267',
 'feature_268',
 'feature_269',
 'feature_270',
 'feature_271',
 'feature_272',
 'feature_273',
 'feature_274',
 'feature_275',
 'feature_276',
 'feature_277',
 'feature_278',
 'feature_279',
 'feature_280',
 'feature_281',
 'feature_282',
 'feature_283',
 'feature_284',
 'feature_285',
 'feature_286',
 'feature_287',
 'feature_288',
 'feature_289',
 'feature_290',
 'feature_291',
 'feature_292',
 'feature_293',
 'feature_294',
 'feature_295',
 'feature_296',
 'feature_297',
 'feature_298',
 'feature_299',
 'feature_300',
 'feature_301',
 'feature_302',
 'feature_303',
 'feature_304',
 'feature_305',
 'feature_306',
 'feature_307',
 'feature_308',
 'feature_309',
 'feature_310',
 'feature_311',
 'feature_312',
 'feature_313',
 'feature_314',
 'feature_315',
 'feature_316',
 'feature_317',
 'feature_318',
 'feature_319',
 'feature_320',
 'feature_321',
 'feature_322',
 'feature_323',
 'feature_324',
 'feature_325',
 'feature_326',
 'feature_327',
 'feature_328',
 'feature_329',
 'feature_330',
 'feature_331',
 'feature_332',
 'feature_333',
 'feature_334',
 'feature_335',
 'feature_336',
 'feature_337',
 'feature_338',
 'feature_339',
 'feature_340',
 'feature_341',
 'feature_342',
 'feature_343',
 'feature_344',
 'feature_345',
 'feature_346',
 'feature_347',
 'feature_348',
 'feature_349',
 'feature_350',
 'feature_351',
 'feature_352',
 'feature_353',
 'feature_354',
 'feature_355',
 'feature_356',
 'feature_357',
 'feature_358',
 'feature_359',
 'feature_360',
 'feature_361',
 'feature_362',
 'feature_363',
 'feature_364',
 'feature_365',
 'feature_366',
 'feature_367',
 'feature_368',
 'feature_369',
 'feature_370',
 'feature_371',
 'feature_372',
 'feature_373',
 'feature_374',
 'feature_375',
 'feature_376',
 'feature_377',
 'feature_378',
 'feature_379',
 'feature_380',
 'feature_381',
 'feature_382',
 'feature_383',
 'feature_384',
 'feature_385',
 'feature_386',
 'feature_387',
 'feature_388',
 'feature_389',
 'feature_390',
 'feature_391',
 'feature_392',
 'feature_393',
 'feature_394',
 'feature_395',
 'feature_396',
 'feature_397',
 'feature_398',
 'feature_399',
 'feature_400',
 'feature_401',
 'feature_402',
 'feature_403',
 'feature_404',
 'feature_405',
 'feature_406',
 'feature_407',
 'feature_408',
 'feature_409',
 'feature_410',
 'feature_411',
 'feature_412',
 'feature_413',
 'feature_414',
 'feature_415',
 'feature_416',
 'feature_417',
 'feature_418',
 'feature_419',
 'feature_420',
 'feature_421',
 'feature_422',
 'feature_423',
 'feature_424',
 'feature_425',
 'feature_426',
 'feature_427',
 'feature_428',
 'feature_429',
 'feature_430',
 'feature_431',
 'feature_432',
 'feature_433',
 'feature_434',
 'feature_435',
 'feature_436',
 'feature_437',
 'feature_438',
 'feature_439',
 'feature_440',
 'feature_441',
 'feature_442',
 'feature_443',
 'feature_444',
 'feature_445',
 'feature_446',
 'feature_447',
 'feature_448',
 'feature_449',
 'feature_450',
 'feature_451',
 'feature_452',
 'feature_453',
 'feature_454',
 'feature_455',
 'feature_456',
 'feature_457',
 'feature_458',
 'feature_459',
 'feature_460',
 'feature_461',
 'feature_462',
 'feature_463',
 'feature_464',
 'feature_465',
 'feature_466',
 'feature_467',
 'feature_468',
 'feature_469',
 'feature_470',
 'feature_471',
 'feature_472',
 'feature_473',
 'feature_474',
 'feature_475',
 'feature_476',
 'feature_477',
 'feature_478',
 'feature_479',
 'feature_480',
 'feature_481',
 'feature_482',
 'feature_483',
 'feature_484',
 'feature_485',
 'feature_486',
 'feature_487',
 'feature_488',
 'feature_489',
 'feature_490',
 'feature_491',
 'feature_492',
 'feature_493',
 'feature_494',
 'feature_495',
 'feature_496',
 'feature_497',
 'feature_498',
 'feature_499',
 'feature_500',
 'feature_501',
 'feature_502',
 'feature_503',
 'feature_504',
 'feature_505',
 'feature_506',
 'feature_507',
 'feature_508',
 'feature_509',
 'feature_510',
 'feature_511',
 'feature_512',
 'feature_513',
 'feature_514',
 'feature_515',
 'feature_516',
 'feature_517',
 'feature_518',
 'feature_519',
 'feature_520',
 'feature_521',
 'feature_522',
 'feature_523',
 'feature_524',
 'feature_525',
 'feature_526',
 'feature_527',
 'feature_528',
 'feature_529',
 'feature_530',
 'feature_531',
 'feature_532',
 'feature_533',
 'feature_534',
 'feature_535',
 'feature_536',
 'feature_537',
 'feature_538',
 'feature_539',
 'feature_540',
 'feature_541',
 'feature_542',
 'feature_543',
 'feature_544',
 'feature_545',
 'feature_546',
 'feature_547',
 'feature_548',
 'feature_549',
 'feature_550',
 'feature_551',
 'feature_552',
 'feature_553',
 'feature_554',
 'feature_555',
 'feature_556',
 'feature_557',
 'feature_558',
 'feature_559',
 'feature_560',
 'feature_561',
 'feature_562',
 'feature_563',
 'feature_564',
 'feature_565',
 'feature_566',
 'feature_567',
 'feature_568',
 'feature_569',
 'feature_570',
 'feature_571',
 'feature_572',
 'feature_573',
 'feature_574',
 'feature_575',
 'feature_576',
 'feature_577',
 'feature_578',
 'feature_579',
 'feature_580',
 'feature_581',
 'feature_582',
 'feature_583',
 'feature_584',
 'feature_585',
 'feature_586',
 'feature_587',
 'feature_588',
 'feature_589',
 'feature_590',
 'feature_591',
 'feature_592',
 'feature_593',
 'feature_594',
 'feature_595',
 'feature_596',
 'feature_597',
 'feature_598',
 'feature_599',
 'feature_600',
 'feature_601',
 'feature_602',
 'feature_603',
 'feature_604',
 'feature_605',
 'feature_606',
 'feature_607',
 'feature_608',
 'feature_609',
 'feature_610',
 'feature_611',
 'feature_612',
 'feature_613',
 'feature_614',
 'feature_615',
 'feature_616',
 'feature_617',
 'feature_618',
 'feature_619',
 'feature_620',
 'feature_621',
 'feature_622',
 'feature_623',
 'feature_624',
 'feature_625',
 'feature_626',
 'feature_627',
 'feature_628',
 'feature_629',
 'feature_630',
 'feature_631',
 'feature_632',
 'feature_633',
 'feature_634',
 'feature_635',
 'feature_636',
 'feature_637',
 'feature_638',
 'feature_639',
 'feature_640',
 'feature_641',
 'feature_642',
 'feature_643',
 'feature_644',
 'feature_645',
 'feature_646',
 'feature_647',
 'feature_648',
 'feature_649',
 'feature_650',
 'feature_651',
 'feature_652',
 'feature_653',
 'feature_654',
 'feature_655',
 'feature_656',
 'feature_657',
 'feature_658',
 'feature_659',
 'feature_660',
 'feature_661',
 'feature_662',
 'feature_663',
 'feature_664',
 'feature_665',
 'feature_666',
 'feature_667',
 'feature_668',
 'feature_669',
 'feature_670',
 'feature_671',
 'feature_672',
 'feature_673',
 'feature_674',
 'feature_675',
 'feature_676',
 'feature_677',
 'feature_678',
 'feature_679',
 'feature_680',
 'feature_681',
 'feature_682',
 'feature_683',
 'feature_684',
 'feature_685',
 'feature_686',
 'feature_687',
 'feature_688',
 'feature_689',
 'feature_690',
 'feature_691',
 'feature_692',
 'feature_693',
 'feature_694',
 'feature_695',
 'feature_696',
 'feature_697',
 'feature_698',
 'feature_699',
 'feature_700',
 'feature_701',
 'feature_702',
 'feature_703',
 'feature_704',
 'feature_705',
 'feature_706',
 'feature_707',
 'feature_708',
 'feature_709',
 'feature_710',
 'feature_711',
 'feature_712',
 'feature_713',
 'feature_714',
 'feature_715',
 'feature_716',
 'feature_717',
 'feature_718',
 'feature_719',
 'feature_720',
 'feature_721',
 'feature_722',
 'feature_723',
 'feature_724',
 'feature_725',
 'feature_726',
 'feature_727',
 'feature_728',
 'feature_729',
 'feature_730',
 'feature_731',
 'feature_732',
 'feature_733',
 'feature_734',
 'feature_735',
 'feature_736',
 'feature_737',
 'feature_738',
 'feature_739',
 'feature_740',
 'feature_741',
 'feature_742',
 'feature_743',
 'feature_744',
 'feature_745',
 'feature_746',
 'feature_747',
 'feature_748',
 'feature_749',
 'feature_750',
 'feature_751',
 'feature_752',
 'feature_753',
 'feature_754',
 'feature_755',
 'feature_756',
 'feature_757',
 'feature_758',
 'feature_759',
 'feature_760',
 'feature_761',
 'feature_762',
 'feature_763',
 'feature_764',
 'feature_765',
 'feature_766',
 'feature_767',
 'feature_768',
 'label']

In [19]:
# Define window_size (number of timesteps or number of frames), number of features, and number of output step
window_size = 120 # number of frames within a window
lag_sampling =  5 # step size for selecting frames within a window
sliding_stride = 4 # sliding window stride
num_features = len(column_names[:-1])
n_steps_out = 1
n_out_index =  -1

In [20]:
is_save_supervised_features_into_file = True # To reduce memory issue when the variable is set to True

In [21]:
# Reframe as supervised learning by each video file
subsets = df_action['subset'].unique()
df_by_subset = {}

for subset in subsets:
    print(f'Processing subset: {subset}')
    df_action_subset = df_action[df_action['subset'] == subset]
    video_files = df_action_subset['video_file_name'].unique()

    dfs = []
    n_skip = 0
    for i, video_file in enumerate(video_files):
        print(f'Processing video file {i+1}/{len(video_files)}: {video_file}'.ljust(200), end='\r')
        
        df_video = df_action_subset[df_action_subset['video_file_name'] == video_file]

        if df_video.shape[0] < int(window_size/lag_sampling):
            n_skip += 1
            continue
        elif df_video.shape[0] < window_size:
            # Pad 0 first 512 columns to make sure we have enough frames within a window
            pad_width = window_size - df_video.shape[0] + 1
            df_video = pd.concat([df_video, pd.DataFrame(np.nan, index=np.arange(pad_width), columns=df_video.columns[:-3])], ignore_index=True)
            # Fill NaN value on first 512 columns values by mode of each column
            df_video.iloc[:, :-3].fillna(df_video.iloc[:, :-3].mode(), inplace=True)
            # Fill NaN values on last 3 column by previous values
            df_video.ffill(inplace=True)

        df_reframed = series_to_supervised(
            df_video.drop(columns=['video_file_name', 'subset']),
            column_names,
            n_in=window_size,
            n_out=n_steps_out,
            n_out_index=n_out_index,
            is_drop_target=True,
            lag_sampling=lag_sampling,
            sliding_stride=sliding_stride
        )
        
        if is_save_supervised_features_into_file:
            # Check if dataframe is not empty
            if not df_reframed.empty:
                df_reframed.to_csv(f'../datasets/supervised_features_tmp/{subset}/supervised_features_{image_encoder_type}_{video_file}.csv', index=False)
        else:
            dfs.append(df_reframed)

    if not is_save_supervised_features_into_file:
        df_subset = pd.concat(dfs, ignore_index=True)
        df_by_subset[subset] = df_subset
    print(f"Finished processing subset: {subset}. Skipped {n_skip} videos.".ljust(200))

Processing subset: train
Finished processing subset: train. Skipped 9 videos.
Processing subset: val
Finished processing subset: val. Skipped 1 videos.
Processing subset: test
Finished processing subset: test. Skipped 2 videos.

In [22]:
import os

if is_save_supervised_features_into_file:
    for subset in subsets:
        print(f'Loading saved supervised features for subset: {subset}')
        all_files = os.listdir(f'../datasets/supervised_features_tmp/{subset}')
        df_by_subset[subset] = pd.concat([pd.read_csv(f'../datasets/supervised_features_tmp/{subset}/{file}') for file in all_files], ignore_index=True)

Loading saved supervised features for subset: train
Loading saved supervised features for subset: val
Loading saved supervised features for subset: test

In [23]:
df_by_subset['train'].head()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_760(t-5),feature_761(t-5),feature_762(t-5),feature_763(t-5),feature_764(t-5),feature_765(t-5),feature_766(t-5),feature_767(t-5),feature_768(t-5),label(t)
0,1.547449,2.130957,0.457726,-0.865287,-2.240753,-4.250560,0.881796,0.334853,0.881861,-1.199312,...,-1.884708,0.232295,3.337499,0.928302,1.395529,2.022104,0.662777,-2.092280,1.153472,normal
1,-0.921097,0.158583,-1.944496,-0.678813,1.548150,-1.079035,-0.808304,1.541112,3.060222,0.865492,...,-2.083093,-0.617584,2.430381,-0.904652,1.100306,-0.481903,0.272392,-1.197223,1.868901,normal
2,0.732105,-0.814530,-1.504126,-0.551601,-0.651063,-2.911235,1.286657,2.231412,2.357542,-0.142958,...,-2.776013,-1.979863,0.434247,-0.784687,0.685439,-1.946032,-0.038194,-0.986495,0.198262,normal
3,0.648934,0.272410,-0.126850,-0.253913,-5.638488,-1.037088,-0.322406,1.698519,0.604000,0.085870,...,-0.548893,-0.934393,2.130732,0.273953,1.245769,-1.833268,1.656364,1.618835,-2.325376,normal
4,1.214411,-0.867668,-1.478303,-1.014128,-5.964977,-1.934494,0.721189,1.687451,-0.609061,-0.308794,...,-1.318516,-0.000010,1.688883,0.081505,1.934987,-1.698160,1.481270,0.510800,-1.353097,normal

In [24]:
# Check dataframes size for each subset
for key in df_by_subset.keys():
    print(f'Subset: {key}, Shape: {df_by_subset[key].shape}')

Subset: train, Shape: (213009, 18433)
Subset: val, Shape: (37674, 18433)
Subset: test, Shape: (46742, 18433)

In [25]:
# Rename label column
for key in df_by_subset.keys():
    df_by_subset[key].rename(columns={f'label(t)': 'label'}, inplace=True)

In [26]:
# Check label distribution for each subset
for key in df_by_subset.keys():
    print(f'Subset: {key} \n{df_by_subset[key]["label"].value_counts()}')

Subset: train
label
abnormal    148412
normal       64597
Name: count, dtype: int64
Subset: val
label
normal      22021
abnormal    15653
Name: count, dtype: int64
Subset: test
label
abnormal    25630
normal      21112
Name: count, dtype: int64

In [27]:
# Define sample size for each subset
sample_size = {
    'train': 120000,
    'val': 15000,
    'test': 15000
}

In [28]:
# Sample data for each subset
df_train = pd.concat([df_by_subset['train'][df_by_subset['train']['label'] == label].sample(n=int(sample_size['train']/2), random_state=SEED) for label in df_by_subset['train']['label'].unique()])
df_train.shape

(120000, 18433)

In [29]:
df_val = pd.concat([df_by_subset['val'][df_by_subset['val']['label'] == label].sample(n=int(sample_size['val']/2), random_state=SEED) for label in df_by_subset['val']['label'].unique()])
df_val.shape

(15000, 18433)

In [30]:
df_test = pd.concat([df_by_subset['test'][df_by_subset['test']['label'] == label].sample(n=int(sample_size['test']/2), random_state=SEED) for label in df_by_subset['test']['label'].unique()])
df_test.shape

(15000, 18433)

In [32]:
# Check label distribution after sampling
print(f'Train label distribution:\n{df_train["label"].value_counts()}') 
print(f'Validation label distribution:\n{df_val["label"].value_counts()}')
print(f'Test label distribution:\n{df_test["label"].value_counts()}')

Train label distribution:
label
normal      60000
abnormal    60000
Name: count, dtype: int64
Validation label distribution:
label
normal      7500
abnormal    7500
Name: count, dtype: int64
Test label distribution:
label
normal      7500
abnormal    7500
Name: count, dtype: int64

In [33]:
# Convert labels to binary (0: abnormal, 1: normal)
df_train['label'] = df_train['label'].map(lambda x: 0 if x == 'normal' else 1)
df_val['label'] = df_val['label'].map(lambda x: 0 if x == 'normal' else 1)
df_test['label'] = df_test['label'].map(lambda x: 0 if x == 'normal' else 1)

In [34]:
df_train.head()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_760(t-5),feature_761(t-5),feature_762(t-5),feature_763(t-5),feature_764(t-5),feature_765(t-5),feature_766(t-5),feature_767(t-5),feature_768(t-5),label
13312,-1.001939,-1.381007,0.633531,0.429163,-0.298200,-0.453133,2.247283,1.954587,0.532277,0.080714,...,-1.217009,-1.583918,-0.298143,-0.963584,1.779241,-1.298116,2.628863,-0.376668,1.881257,0
189940,-0.167828,-0.138051,0.004061,0.718687,-0.212446,0.557625,1.170994,1.548742,3.045085,-0.610688,...,-0.514316,-1.040187,0.146528,-1.109582,0.578558,0.966183,-0.257191,0.543282,-0.952265,0
178140,-0.418083,0.989029,0.304729,-0.032815,-1.372137,0.759515,-0.239332,0.671136,-1.108282,0.763403,...,0.184783,0.210102,-0.705324,-0.593209,-0.612645,0.686541,2.852654,0.962284,-0.533169,0
182076,0.191408,2.465957,-0.020650,-0.520323,1.034067,-2.764348,-0.256112,2.337351,0.180808,1.109622,...,-0.209027,0.154073,0.651650,2.305388,0.108988,-0.155406,-0.129435,-1.079135,0.464676,0
179860,-1.493059,0.789074,0.672941,0.394710,-1.365071,-0.833353,-0.044438,1.418517,-0.149013,0.268304,...,-1.756041,-0.378253,0.009360,1.013259,-1.257778,-0.258186,-0.047683,0.780812,-0.728086,0

In [35]:
df_train.tail()

,feature_1(t-120),feature_2(t-120),feature_3(t-120),feature_4(t-120),feature_5(t-120),feature_6(t-120),feature_7(t-120),feature_8(t-120),feature_9(t-120),feature_10(t-120),...,feature_760(t-5),feature_761(t-5),feature_762(t-5),feature_763(t-5),feature_764(t-5),feature_765(t-5),feature_766(t-5),feature_767(t-5),feature_768(t-5),label
109182,0.394228,-0.855858,0.120808,-0.304345,1.735282,-3.185258,1.145306,2.793064,1.065596,1.842435,...,-3.105960,-2.875577,1.053101,1.657330,1.333245,-0.068779,0.081246,-0.964124,1.963882,1
30797,-1.184941,0.151227,0.305448,0.517507,0.320752,-1.986891,0.799942,1.093807,1.184337,-2.078866,...,1.500935,-0.881573,0.303289,-0.952156,0.721310,-2.579802,0.920185,1.667218,3.451152,1
99296,-2.600614,-1.407992,0.564344,-0.087325,-2.515818,1.567645,1.256438,3.524784,3.505120,-1.980888,...,-0.555135,0.263197,0.716045,2.822711,-1.491435,-1.381807,-0.728145,0.274710,0.465401,1
146652,-0.778160,-0.605017,-0.472527,-1.019190,-1.021873,-2.715089,0.297932,2.404969,1.473728,2.257737,...,-2.226174,-0.247151,1.135848,-1.458785,3.934632,0.253987,1.158248,-1.252816,-0.155307,1
65752,-1.660565,-1.926210,0.726194,0.065926,-6.576314,0.736182,0.658770,1.722298,-0.467237,-0.094240,...,-2.115388,-0.828880,0.943648,1.661857,0.327664,0.399630,1.052080,-2.271787,-1.487886,1

In [36]:
# Reshape data for model training
X_train, y_train = df_train.drop(columns=['label']).values, df_train['label'].values
X_val, y_val = df_val.drop(columns=['label']).values, df_val['label'].values
X_test, y_test = df_test.drop(columns=['label']).values, df_test['label'].values

effective_window_size = int(window_size / lag_sampling)
X_train = X_train.reshape((-1, effective_window_size, num_features))
X_val = X_val.reshape((-1, effective_window_size, num_features))
X_test = X_test.reshape((-1, effective_window_size, num_features))

X_train.shape, y_train.shape, X_val.shape, y_val.shape, X_test.shape, y_test.shape

((120000, 24, 768),
 (120000,),
 (15000, 24, 768),
 (15000,),
 (15000, 24, 768),
 (15000,))

In [37]:
# Save processed data to npz file
np.savez_compressed(f'../datasets/{image_encoder_type}/video_frame_features_{image_encoder_type}_ws{window_size}_ls{lag_sampling}_st{sliding_stride}_supervised_data.npz', 
                    X_train=X_train, y_train=y_train, 
                    X_val=X_val, y_val=y_val, 
                    X_test=X_test, y_test=y_test)